/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Home.gltf 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/Home.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Sofa" position={[7.16, 0.279, -12.375]} rotation={[-Math.PI / 2, 0, 0]} scale={0.003}>
          <mesh name="Sofa001" geometry={nodes.Sofa001.geometry} material={materials.Max_MaterialID_0} position={[-0.332, 458.689, 209.556]} />
          <mesh name="Sofa002" geometry={nodes.Sofa002.geometry} material={materials.Max_MaterialID_0} position={[-2364.648, -597.021, 233.223]} rotation={[0, 0, Math.PI / 2]} scale={[0.866, 1, 1]} />
        </group>
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={nodes.Cube.material} position={[0, 1.114, 0]} rotation={[0, 0, -Math.PI]} scale={[-1, -1, -0.413]} />
        <group name="Cube001" position={[-1.389, 5.592, -9.872]} rotation={[Math.PI, Math.PI / 2, 0]} scale={[-1, -1, -0.413]}>
          <mesh name="Cube002_1" geometry={nodes.Cube002_1.geometry} material={materials['Material.001']} />
          <mesh name="Cube002_2" geometry={nodes.Cube002_2.geometry} material={materials['Material.002']} />
        </group>
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={nodes.Plane.material} position={[0, 0, -0.617]} />
        <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} position={[5.972, 3.001, -1.426]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-4.679, -0.098, -1]} />
        <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={nodes.Cube003.material} position={[8.855, 1, -1.366]} />
        <mesh name="Cube004" geometry={nodes.Cube004.geometry} material={nodes.Cube004.material} position={[8.888, 0.307, -1.455]} scale={[0.838, 0.202, 1]} />
        <mesh name="Cube005" geometry={nodes.Cube005.geometry} material={nodes.Cube005.material} position={[8.888, 0.78, -1.455]} scale={[0.838, 0.202, 1]} />
        <mesh name="Cube006" geometry={nodes.Cube006.geometry} material={nodes.Cube006.material} position={[8.888, 1.25, -1.455]} scale={[0.838, 0.202, 1]} />
        <mesh name="Cube007" geometry={nodes.Cube007.geometry} material={nodes.Cube007.material} position={[8.888, 1.719, -1.455]} scale={[0.838, 0.202, 1]} />
        <mesh name="Cube008" geometry={nodes.Cube008.geometry} material={nodes.Cube008.material} position={[8.888, 2.189, -1.455]} scale={[0.838, 0.202, 1]} />
        <mesh name="Cube009" geometry={nodes.Cube009.geometry} material={nodes.Cube009.material} position={[8.888, 2.658, -1.455]} scale={[0.838, 0.202, 1]} />
        <mesh name="Cube010" geometry={nodes.Cube010.geometry} material={materials['Material.005']} position={[2.612, 1, -1.366]} />
        <mesh name="Cube011" geometry={nodes.Cube011.geometry} material={nodes.Cube011.material} position={[2.644, 0.307, -1.455]} scale={[0.838, 0.202, 1]} />
        <mesh name="Cube012" geometry={nodes.Cube012.geometry} material={nodes.Cube012.material} position={[2.644, 0.78, -1.455]} scale={[0.838, 0.202, 1]} />
        <mesh name="Cube013" geometry={nodes.Cube013.geometry} material={nodes.Cube013.material} position={[2.644, 1.25, -1.455]} scale={[0.838, 0.202, 1]} />
        <mesh name="Cube014" geometry={nodes.Cube014.geometry} material={nodes.Cube014.material} position={[2.644, 1.719, -1.455]} scale={[0.838, 0.202, 1]} />
        <mesh name="Cube015" geometry={nodes.Cube015.geometry} material={nodes.Cube015.material} position={[2.644, 2.189, -1.455]} scale={[0.838, 0.202, 1]} />
        <mesh name="Cube016" geometry={nodes.Cube016.geometry} material={nodes.Cube016.material} position={[2.644, 2.658, -1.455]} scale={[0.838, 0.202, 1]} />
        <mesh name="Cube017" geometry={nodes.Cube017.geometry} material={nodes.Cube017.material} position={[0.04, 1.015, -5.004]} />
        <mesh name="Cube018" geometry={nodes.Cube018.geometry} material={nodes.Cube018.material} position={[6.832, 0.438, -9.974]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-1.659, -0.456, -1.659]} />
        <mesh name="Cube020" geometry={nodes.Cube020.geometry} material={nodes.Cube020.material} position={[6.832, 1.769, -9.974]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-1.659, -0.456, -1.659]} />
        <mesh name="Cube019" geometry={nodes.Cube019.geometry} material={nodes.Cube019.material} position={[-0.912, 8.514, -12.226]} scale={[0.079, 0.095, 1]} />
        <mesh name="Cube021" geometry={nodes.Cube021.geometry} material={nodes.Cube021.material} position={[-0.981, 8.407, -12.14]} rotation={[-Math.PI, 0, -0.377]} scale={[-0.016, -0.048, -0.959]} />
        <mesh name="Cube022" geometry={nodes.Cube022.geometry} material={nodes.Cube022.material} position={[-0.912, 3.514, -12.226]} scale={[0.079, 0.095, 1]} />
        <mesh name="Cube023" geometry={nodes.Cube023.geometry} material={nodes.Cube023.material} position={[-0.912, 6.011, -9.439]} scale={[0.079, 0.095, 0.032]} />
        <mesh name="Cube024" geometry={nodes.Cube024.geometry} material={nodes.Cube024.material} position={[-0.912, 6.011, -15.01]} scale={[0.079, 0.095, 0.032]} />
        <mesh name="BézierCurve" geometry={nodes.BézierCurve.geometry} material={nodes.BézierCurve.material} position={[-0.876, 5.86, -14.861]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={4.734} />
        <group name="Screen" position={[6.072, 4.417, -0.535]} rotation={[0, 0, -Math.PI]} scale={[-15.088, -7.496, -0.112]}>
          <mesh name="Cube037" geometry={nodes.Cube037.geometry} material={materials['Material.006']} />
          <mesh name="Cube037_1" geometry={nodes.Cube037_1.geometry} material={materials['Material.007']} />
        </group>
        <mesh name="Cube026" geometry={nodes.Cube026.geometry} material={nodes.Cube026.material} position={[2.435, 3.898, -1.521]} scale={[2.79, 5.805, 5.805]} />
        <mesh name="Keyboard" geometry={nodes.Keyboard.geometry} material={nodes.Keyboard.material} position={[6.058, 3.123, -1.786]} scale={[0.19, 0.064, 0.19]} />
        <mesh name="Cube025" geometry={nodes.Cube025.geometry} material={nodes.Cube025.material} position={[6.143, 6.551, -0.655]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-2.427, -0.045, -0.291]} />
        <group name="Cube039" position={[9.571, 5.79, -0.418]} rotation={[-Math.PI, -1.571, 0]} scale={[0.058, 1.437, 1.437]}>
          <mesh name="Cube164" geometry={nodes.Cube164.geometry} material={materials['Material.009']} />
          <mesh name="Cube164_1" geometry={nodes.Cube164_1.geometry} material={materials['Material.010']} />
        </group>
        <mesh name="Cube045" geometry={nodes.Cube045.geometry} material={materials['Material.004']} position={[10.972, 4.909, -0.418]} rotation={[0, Math.PI / 2, 0]} scale={[0.058, 1.437, 1.437]} />
        <group name="Vancouver_002" position={[6, 0, -4]} rotation={[Math.PI / 2, 0, 0]} scale={0.004}>
          <mesh name="Vancouver_002_1" geometry={nodes.Vancouver_002_1.geometry} material={materials.wire_204204204} />
          <mesh name="Vancouver_002_2" geometry={nodes.Vancouver_002_2.geometry} material={materials.wire_057008136} />
          <mesh name="Vancouver_002_3" geometry={nodes.Vancouver_002_3.geometry} material={materials.wire_145028177} />
          <mesh name="Vancouver_002_4" geometry={nodes.Vancouver_002_4.geometry} material={materials.wire_149149149} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Home.gltf')

